import {
  Tenant,
  Category,
  Product,
  BlogPost,
  SiteSettings,
  Order,
  PromoCode,
  ProductReview,
  AbandonedCart,
  UserAccount,
  CategoryRequest,
} from './types';

export const mockSiteSettings: SiteSettings = {
  id: 'default',
  storeName: 'Volvelo',
  tagline: 'Consciously Crafted Luxury Essentials & European Haute Craft',
  logoUrl: null,
  contactEmail: 'concierge@volvelo.com',
  contactPhone: '+49 30 555 3829',
  currencySymbol: '€',
  currencyCode: 'EUR',
  announcementText: 'Complimentary carbon-neutral express shipping across Europe on orders over €50',
  defaultMetaTitle: 'Volvelo — Luxury Men & Women Timepieces, Footwear, Atelier Apparel & Fine Jewellery',
  defaultMetaDescription: 'Discover handcrafted Swiss chronographs, Italian leather footwear, silk apparel, and 18k fine jewellery directly from verified European ateliers.',
  lowStockThreshold: 3,
  shippingBadgeTitle: 'EU Express',
  shippingBadgeSubtitle: '2-4 Days Direct',
  returnsBadgeTitle: '7 Days',
  returnsBadgeSubtitle: 'Complimentary Returns',
  guaranteeBadgeTitle: 'Guaranteed',
  guaranteeBadgeSubtitle: '100% Verified Atelier',
  freeShippingThreshold: 50,
  standardShippingFee: 4.9,
  carbonNeutralBadge: '100% Climate Neutral Delivery',
  autoApproveMerchants: false,
  defaultCommissionRate: 15,
};

export const mockTenants: Tenant[] = [
  {
    id: 'tenant-volvelo',
    name: 'Volvelo Design Studio',
    slug: 'volvelo-studio',
    logo: null,
    status: 'ACTIVE',
    email: 'studio@volvelo.com',
    country: 'Germany',
    city: 'Berlin',
    story: 'In-house European design laboratory creating timeless minimalist silhouettes and curated luxury staples.',
    website: 'https://volvelo.com',
    commissionRate: 0,
    contactPerson: 'Head Curator',
    ecoBadges: ['In-House Atelier', 'Circular Design', 'Climate Neutral'],
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'tenant-geneva',
    name: "L'Atelier Horloger Genève",
    slug: 'atelier-horloger-geneve',
    logo: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=200&q=80',
    status: 'ACTIVE',
    email: 'contact@horloger-geneve.ch',
    country: 'Switzerland',
    city: 'Geneva',
    story: 'Centuries-old Swiss horological craftsmanship assembling scratch-resistant sapphire crystal automatic chronographs and petite luxury dials.',
    website: 'https://horloger-geneve.ch',
    commissionRate: 15,
    contactPerson: 'Marc Dufour',
    ecoBadges: ['Swiss Made Certified', 'Sapphire Glass', '5 ATM Water Resistant'],
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2025-01-05'),
  },
  {
    id: 'tenant-firenze',
    name: 'Bottega Calzature Firenze',
    slug: 'calzature-firenze',
    logo: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=200&q=80',
    status: 'ACTIVE',
    email: 'info@calzaturefirenze.it',
    country: 'Italy',
    city: 'Florence',
    story: 'Tuscan master cordwainers hand-lasting full-grain vegetable-tanned loafers, Blake-stitched oxfords, and sculptural Italian heels.',
    website: 'https://calzaturefirenze.it',
    commissionRate: 15,
    contactPerson: 'Matteo Rossi',
    ecoBadges: ['Handcrafted in Tuscany', 'Vegetable-Tanned Leather', 'Blake Stitch Construction'],
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date('2025-01-10'),
  },
  {
    id: 'tenant-paris',
    name: 'Maison de Haute Parure',
    slug: 'maison-haute-parure',
    logo: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=200&q=80',
    status: 'ACTIVE',
    email: 'joaillerie@hauteparure.fr',
    country: 'France',
    city: 'Paris',
    story: 'Place Vendôme trained high jewellery studio forging recycled 18k solid gold drop earrings, conflict-free solitaire diamonds, and tennis bracelets.',
    website: 'https://hauteparure.fr',
    commissionRate: 15,
    contactPerson: 'Claire Chevalier',
    ecoBadges: ['18K Recycled Solid Gold', 'Conflict-Free Diamonds', 'RJC Certified'],
    createdAt: new Date('2025-01-12'),
    updatedAt: new Date('2025-01-12'),
  },
  {
    id: 'tenant-milan',
    name: 'Sartoria Tessile Milano',
    slug: 'sartoria-milano',
    logo: 'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=200&q=80',
    status: 'ACTIVE',
    email: 'atelier@sartoriamilano.it',
    country: 'Italy',
    city: 'Milan',
    story: 'Lombardy textile maison weaving heavy mulberry silks, double-faced cashmere overcoats, and impeccably tailored women silhouettes.',
    website: 'https://sartoriamilano.it',
    commissionRate: 15,
    contactPerson: 'Gianluca Conti',
    ecoBadges: ['100% Mulberry Silk', 'Cariaggi Cashmere', 'OEKO-TEX Certified'],
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-01-15'),
  },
];

export const mockCategories: Category[] = [
  {
    id: 'cat-men',
    name: 'Men',
    slug: 'men',
    description: "Curated men's horology and handcrafted Italian leather footwear.",
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    seoTitle: "Men's Luxury Watches & Handcrafted Shoes | Volvelo",
    seoDescription: "Explore men's Swiss chronographs, automatic timepieces, Tuscan leather loafers, and dress oxfords.",
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
    _count: { products: 5 },
    children: [
      {
        id: 'cat-men-watches',
        name: 'Watches & Timepieces',
        slug: 'men-watches',
        description: 'Swiss sapphire automatic chronographs and minimalist dress watches.',
        parentId: 'cat-men',
      },
      {
        id: 'cat-men-shoes',
        name: 'Footwear & Shoes',
        slug: 'men-shoes',
        description: 'Blake-stitched Italian leather oxfords, suede loafers, and luxury city sneakers.',
        parentId: 'cat-men',
      },
    ],
  },
  {
    id: 'cat-women',
    name: 'Women',
    slug: 'women',
    description: "Exquisite women's atelier apparel, fine jewellery, petite timepieces, and Italian footwear.",
    image: 'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=800&q=80',
    seoTitle: "Women's Designer Clothes, Watches, Shoes & Fine Jewellery | Volvelo",
    seoDescription: "Shop luxury mulberry silk dresses, 18k solid gold earrings, Swiss petite watches, and Italian stiletto heels.",
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
    _count: { products: 13 },
    children: [
      {
        id: 'cat-women-clothes',
        name: 'Atelier Clothes',
        slug: 'women-clothes',
        description: 'Mulberry silk slip dresses, pure cashmere knitwear, wool coats & tailored trousers.',
        parentId: 'cat-women',
      },
      {
        id: 'cat-women-watches',
        name: 'Watches & Timepieces',
        slug: 'women-watches',
        description: 'Milanese rose gold mesh, petite dials, and diamond-accented Swiss watches.',
        parentId: 'cat-women',
      },
      {
        id: 'cat-women-shoes',
        name: 'Footwear & Heels',
        slug: 'women-shoes',
        description: 'Classic stiletto pumps, block heels, artisan loafers, and sleek ankle boots.',
        parentId: 'cat-women',
      },
      {
        id: 'cat-women-jewellery',
        name: 'Fine Jewellery',
        slug: 'women-jewellery',
        description: '18K solid gold drop earrings, diamond solitaire pendants, tennis bracelets & dome rings.',
        parentId: 'cat-women',
      },
    ],
  },
  {
    id: 'cat-men-watches',
    name: "Men's Watches",
    slug: 'men-watches',
    parentId: 'cat-men',
    description: 'Precision Swiss automatic chronographs and minimalist sapphire crystal timepieces.',
    image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=80',
    seoTitle: "Men's Luxury Chronographs & Automatic Watches | Volvelo",
    seoDescription: "Discover master horology with Swiss automatic movements, sapphire crystal, and 5 ATM water resistance.",
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
    _count: { products: 2 },
    children: [
      {
        id: 'sub-men-chronographs',
        name: 'Automatic Chronographs',
        slug: 'men-watches?sub=chronographs',
        description: 'Tri-register Swiss chronographs with 48h power reserve.',
        parentId: 'cat-men-watches',
      },
      {
        id: 'sub-men-dress-watches',
        name: 'Minimalist Dress Watches',
        slug: 'men-watches?sub=dress-watches',
        description: 'Ultra-slim titanium and polished stainless steel dials.',
        parentId: 'cat-men-watches',
      },
    ],
  },
  {
    id: 'cat-men-shoes',
    name: "Men's Shoes",
    slug: 'men-shoes',
    parentId: 'cat-men',
    description: 'Hand-lasted Italian leather oxfords, suede loafers, and minimalist luxury sneakers.',
    image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=80',
    seoTitle: "Handcrafted Men's Italian Leather Shoes & Loafers | Volvelo",
    seoDescription: "Experience Blake-stitched Tuscan leather oxfords, supple suede loafers, and white calfskin sneakers.",
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
    _count: { products: 3 },
    children: [
      {
        id: 'sub-men-loafers',
        name: 'Suede & Leather Loafers',
        slug: 'men-shoes?sub=loafers',
        description: 'Unlined buttery soft Italian suede loafers.',
        parentId: 'cat-men-shoes',
      },
      {
        id: 'sub-men-oxfords',
        name: 'Dress Oxfords & Derbies',
        slug: 'men-shoes?sub=oxfords',
        description: 'Formal full-grain French calfskin shoes.',
        parentId: 'cat-men-shoes',
      },
      {
        id: 'sub-men-sneakers',
        name: 'Minimalist Calfskin Sneakers',
        slug: 'men-shoes?sub=sneakers',
        description: 'Clean-line low top leather sneakers handmade in Portugal.',
        parentId: 'cat-men-shoes',
      },
    ],
  },
  {
    id: 'cat-women-clothes',
    name: "Women's Clothing",
    slug: 'women-clothes',
    parentId: 'cat-women',
    description: 'Mulberry silk slip dresses, fine cashmere knitwear, wool coats, and tailored trousers.',
    image: 'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=800&q=80',
    seoTitle: "Women's Designer Silk Dresses, Cashmere Knitwear & Coats | Volvelo",
    seoDescription: "Tailored in Milan: pure 19-momme silk slip dresses, double-faced wool overcoats, and cashmere sweaters.",
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
    _count: { products: 4 },
    children: [
      {
        id: 'sub-women-dresses',
        name: 'Silk Dresses & Slip Gowns',
        slug: 'women-clothes?sub=dresses',
        description: 'Fluid bias-cut silk dresses for evening and day.',
        parentId: 'cat-women-clothes',
      },
      {
        id: 'sub-women-knitwear',
        name: 'Cashmere & Fine Knitwear',
        slug: 'women-clothes?sub=knitwear',
        description: 'Grade-A Cariaggi cashmere sweaters and cardigans.',
        parentId: 'cat-women-clothes',
      },
      {
        id: 'sub-women-outerwear',
        name: 'Wool Coats & Blazers',
        slug: 'women-clothes?sub=outerwear',
        description: 'Structured double-breasted overcoats tailored in Italy.',
        parentId: 'cat-women-clothes',
      },
      {
        id: 'sub-women-trousers',
        name: 'Tailored Trousers & Pants',
        slug: 'women-clothes?sub=trousers',
        description: 'High-rise pleated virgin wool trousers.',
        parentId: 'cat-women-clothes',
      },
    ],
  },
  {
    id: 'cat-women-watches',
    name: "Women's Watches",
    slug: 'women-watches',
    parentId: 'cat-women',
    description: 'Petite dials, Milanese rose gold mesh straps, and diamond-set Swiss timepieces.',
    image: 'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&w=800&q=80',
    seoTitle: "Women's Luxury Rose Gold & Swiss Diamond Watches | Volvelo",
    seoDescription: "Elegantly proportioned 28mm-32mm dials with Milanese mesh bands and scratch-resistant sapphire glass.",
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
    _count: { products: 2 },
    children: [
      {
        id: 'sub-women-rosegold',
        name: 'Rose Gold & Mesh Watches',
        slug: 'women-watches?sub=rosegold',
        description: 'Ultra-thin Milanese mesh watches with sunburst dial.',
        parentId: 'cat-women-watches',
      },
      {
        id: 'sub-women-diamond-watches',
        name: 'Diamond & Petite Dials',
        slug: 'women-watches?sub=diamond',
        description: '28mm petite dials accented with certified diamond markers.',
        parentId: 'cat-women-watches',
      },
    ],
  },
  {
    id: 'cat-women-shoes',
    name: "Women's Shoes",
    slug: 'women-shoes',
    parentId: 'cat-women',
    description: 'Handcrafted Italian pumps, block heels, smooth leather loafers, and sleek ankle boots.',
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
    seoTitle: "Designer Women's Italian Heels, Flats & Ankle Boots | Volvelo",
    seoDescription: "Walk in effortless elegance with 85mm stiletto pumps, glove-soft leather flats, and Tuscan Chelsea boots.",
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
    _count: { products: 3 },
    children: [
      {
        id: 'sub-women-heels',
        name: 'Stiletto & Block Heels',
        slug: 'women-shoes?sub=heels',
        description: 'Ergonomically cushioned Italian pumps for all-day grace.',
        parentId: 'cat-women-shoes',
      },
      {
        id: 'sub-women-flats',
        name: 'Pointed Loafers & Flats',
        slug: 'women-shoes?sub=flats',
        description: 'Soft butter-calf flats with cushioned memory leather insoles.',
        parentId: 'cat-women-shoes',
      },
      {
        id: 'sub-women-boots',
        name: 'Sleek Chelsea & Ankle Boots',
        slug: 'women-shoes?sub=boots',
        description: 'Water-resistant Italian leather boots with sculpted silhouette.',
        parentId: 'cat-women-shoes',
      },
    ],
  },
  {
    id: 'cat-women-jewellery',
    name: 'Fine Jewellery',
    slug: 'women-jewellery',
    parentId: 'cat-women',
    description: '18K solid gold drop earrings, diamond solitaire necklaces, tennis bracelets & dome rings.',
    image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=800&q=80',
    seoTitle: "18K Solid Gold Fine Jewellery, Earrings & Diamond Pendants | Volvelo",
    seoDescription: "Forged in Paris: ethical 18k solid gold sculptural earrings, conflict-free diamond chokers, and tennis bracelets.",
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
    _count: { products: 4 },
    children: [
      {
        id: 'sub-jewellery-earrings',
        name: 'Earrings (Studs & Drops)',
        slug: 'women-jewellery?sub=earrings',
        description: 'Sculptural 18k solid gold drop earrings and diamond huggies.',
        parentId: 'cat-women-jewellery',
      },
      {
        id: 'sub-jewellery-necklaces',
        name: 'Necklaces & Pendants',
        slug: 'women-jewellery?sub=necklaces',
        description: 'Delicate gold chain necklaces with solitaire lab-grown diamond pendants.',
        parentId: 'cat-women-jewellery',
      },
      {
        id: 'sub-jewellery-bracelets',
        name: 'Bracelets & Bangles',
        slug: 'women-jewellery?sub=bracelets',
        description: 'Micro-pavé diamond tennis bracelets and solid gold cuff bangles.',
        parentId: 'cat-women-jewellery',
      },
      {
        id: 'sub-jewellery-rings',
        name: 'Statement & Band Rings',
        slug: 'women-jewellery?sub=rings',
        description: 'Fluted 18k gold dome rings and stackable eternity bands.',
        parentId: 'cat-women-jewellery',
      },
    ],
  },
];

export const mockProducts: Product[] = [
  // ==================== MEN'S WATCHES ====================
  {
    id: 'prod-geneva-chronograph',
    tenantId: 'tenant-geneva',
    categoryId: 'cat-men-watches',
    title: 'Geneva Grand Automatic Chronograph 41mm',
    slug: 'geneva-grand-automatic-chronograph',
    description: 'Assembled in Geneva by master watchmakers, the Grand Chronograph features a certified Swiss automatic movement with a 48-hour power reserve, anti-reflective sapphire crystal, and an exhibition case back. Water-resistant to 50 meters (5 ATM).',
    basePrice: 420,
    compareAtPrice: 510,
    isFeatured: true,
    status: 'ACTIVE',
    seoScore: 96.5,
    seoTitle: 'Geneva Grand Automatic Chronograph 41mm — Swiss Horology | Volvelo',
    seoDescription: 'Masterfully assembled in Switzerland. Features a 48-hour automatic movement, anti-reflective sapphire crystal, and genuine calfskin strap.',
    tags: ['men', 'watches', 'chronograph', 'swiss-made', 'sapphire', 'luxury'],
    viewsCount: 2310,
    cartAddCount: 310,
    ordersCount: 112,
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date('2025-01-10'),
    images: [
      {
        id: 'img-chrono-1',
        productId: 'prod-geneva-chronograph',
        url: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1200&q=80',
        altText: 'Geneva Grand Chronograph front dial perspective',
        order: 0,
      },
      {
        id: 'img-chrono-2',
        productId: 'prod-geneva-chronograph',
        url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80',
        altText: 'Geneva Grand Chronograph wrist detail and crown',
        order: 1,
      },
    ],
    variants: [
      {
        id: 'var-chrono-blk-leather',
        productId: 'prod-geneva-chronograph',
        sku: 'CHRONO-GEN-BLK-LTH',
        price: 420,
        compareAtPrice: 510,
        stock: 6,
        image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1200&q=80',
        optionValues: { 'Dial Color': 'Onyx Black', Strap: 'Italian Calf Leather' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'var-chrono-emr-mesh',
        productId: 'prod-geneva-chronograph',
        sku: 'CHRONO-GEN-EMR-MSH',
        price: 445,
        compareAtPrice: 535,
        stock: 4,
        image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80',
        optionValues: { 'Dial Color': 'Emerald Sunburst', Strap: 'Stainless Steel Mesh' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 'prod-titanium-dress-watch',
    tenantId: 'tenant-geneva',
    categoryId: 'cat-men-watches',
    title: 'Minimalist Titanium Slim Dress Watch 38mm',
    slug: 'minimalist-titanium-slim-dress-watch',
    description: 'Engineered from aerospace-grade satin titanium, this ultra-slim 6.8mm profile timepiece slips effortlessly beneath a tailored French cuff. Features Swiss quartz movement and scratch-resistant sapphire crystal.',
    basePrice: 280,
    compareAtPrice: 340,
    isFeatured: true,
    status: 'ACTIVE',
    seoScore: 92.0,
    seoTitle: 'Minimalist Titanium Slim Dress Watch 38mm | Volvelo',
    seoDescription: 'Ultra-slim 6.8mm titanium dress watch with sapphire crystal and quick-release genuine leather strap.',
    tags: ['men', 'watches', 'titanium', 'minimalist', 'dress-watch'],
    viewsCount: 1680,
    cartAddCount: 220,
    ordersCount: 74,
    createdAt: new Date('2025-01-14'),
    updatedAt: new Date('2025-01-14'),
    images: [
      {
        id: 'img-titan-1',
        productId: 'prod-titanium-dress-watch',
        url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80',
        altText: 'Minimalist Titanium Watch in Silver Sunray dial',
        order: 0,
      },
    ],
    variants: [
      {
        id: 'var-titan-slv-cognac',
        productId: 'prod-titanium-dress-watch',
        sku: 'TITAN-SLV-COG',
        price: 280,
        compareAtPrice: 340,
        stock: 9,
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80',
        optionValues: { 'Dial Color': 'Silver Sunray', Strap: 'Cognac Leather' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'var-titan-blk-blk',
        productId: 'prod-titanium-dress-watch',
        sku: 'TITAN-BLK-BLK',
        price: 280,
        compareAtPrice: 340,
        stock: 5,
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80',
        optionValues: { 'Dial Color': 'Midnight Black', Strap: 'Black Leather' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },

  // ==================== MEN'S SHOES ====================
  {
    id: 'prod-florence-suede-loafer',
    tenantId: 'tenant-firenze',
    categoryId: 'cat-men-shoes',
    title: 'Handcrafted Florence Unlined Suede Loafers',
    slug: 'handcrafted-florence-unlined-suede-loafers',
    description: 'Handcrafted in Florence using buttery unlined Tuscan reverse-suede. Extremely supple, featherlight, and finished with a flexible hand-stitched leather sole for effortless Mediterranean elegance.',
    basePrice: 195,
    compareAtPrice: 240,
    isFeatured: true,
    status: 'ACTIVE',
    seoScore: 95.0,
    seoTitle: 'Florence Unlined Suede Loafers — Handmade in Italy | Volvelo',
    seoDescription: 'Hand-lasted Italian suede loafers crafted with Blake construction and glove-soft leather insoles.',
    tags: ['men', 'shoes', 'loafers', 'suede', 'made-in-italy', 'florence'],
    viewsCount: 3100,
    cartAddCount: 410,
    ordersCount: 165,
    createdAt: new Date('2025-01-08'),
    updatedAt: new Date('2025-01-08'),
    images: [
      {
        id: 'img-loafer-1',
        productId: 'prod-florence-suede-loafer',
        url: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=1200&q=80',
        altText: 'Florence Suede Loafer in Snuff Brown detail',
        order: 0,
      },
    ],
    variants: [
      {
        id: 'var-loafer-brown-42',
        productId: 'prod-florence-suede-loafer',
        sku: 'LOAFER-SNUFF-42',
        price: 195,
        compareAtPrice: 240,
        stock: 5,
        image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Color: 'Snuff Suede', Size: 'EU 42' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'var-loafer-brown-43',
        productId: 'prod-florence-suede-loafer',
        sku: 'LOAFER-SNUFF-43',
        price: 195,
        compareAtPrice: 240,
        stock: 8,
        image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Color: 'Snuff Suede', Size: 'EU 43' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'var-loafer-navy-42',
        productId: 'prod-florence-suede-loafer',
        sku: 'LOAFER-NAVY-42',
        price: 195,
        compareAtPrice: 240,
        stock: 4,
        image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Color: 'Midnight Navy', Size: 'EU 42' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 'prod-lisbon-leather-oxford',
    tenantId: 'tenant-firenze',
    categoryId: 'cat-men-shoes',
    title: 'Lisbon Full-Grain French Calfskin Oxford',
    slug: 'lisbon-full-grain-calfskin-oxford',
    description: 'The pinnacle of black-tie and executive footwear. Hand-cut from Grade-A French box-calf with closed-channel Blake welt stitching and bevelled waist.',
    basePrice: 240,
    compareAtPrice: 295,
    isFeatured: false,
    status: 'ACTIVE',
    seoScore: 91.0,
    seoTitle: 'Lisbon French Box-Calf Oxford Shoes | Volvelo',
    seoDescription: 'Hand-dyed full-grain leather oxford with leather outsole and brass nail accents.',
    tags: ['men', 'shoes', 'oxford', 'leather', 'formal'],
    viewsCount: 1200,
    cartAddCount: 140,
    ordersCount: 42,
    createdAt: new Date('2025-01-20'),
    updatedAt: new Date('2025-01-20'),
    images: [
      {
        id: 'img-oxford-1',
        productId: 'prod-lisbon-leather-oxford',
        url: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=1200&q=80',
        altText: 'Lisbon Full-Grain Oxford in Deep Espresso',
        order: 0,
      },
    ],
    variants: [
      {
        id: 'var-oxford-blk-42',
        productId: 'prod-lisbon-leather-oxford',
        sku: 'OXFORD-BLK-42',
        price: 240,
        compareAtPrice: 295,
        stock: 4,
        image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Color: 'Noir Black', Size: 'EU 42' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'var-oxford-blk-43',
        productId: 'prod-lisbon-leather-oxford',
        sku: 'OXFORD-BLK-43',
        price: 240,
        compareAtPrice: 295,
        stock: 6,
        image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Color: 'Noir Black', Size: 'EU 43' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 'prod-monaco-calfskin-sneaker',
    tenantId: 'tenant-volvelo',
    categoryId: 'cat-men-shoes',
    title: 'Monaco Minimalist White Calfskin Sneaker',
    slug: 'monaco-minimalist-white-calfskin-sneaker',
    description: 'Clean-cut luxury sneaker handcrafted from Italian nappa calf leather and Margom natural rubber outsoles. Gold-embossed serial stamp and wax-cotton laces.',
    basePrice: 165,
    compareAtPrice: 200,
    isFeatured: true,
    status: 'ACTIVE',
    seoScore: 93.0,
    seoTitle: 'Monaco Minimalist White Calfskin Sneaker | Volvelo',
    seoDescription: 'Handcrafted luxury white sneaker featuring Italian nappa leather and Margom soles.',
    tags: ['men', 'shoes', 'sneakers', 'leather', 'minimalist'],
    viewsCount: 2800,
    cartAddCount: 390,
    ordersCount: 140,
    createdAt: new Date('2025-01-18'),
    updatedAt: new Date('2025-01-18'),
    images: [
      {
        id: 'img-snk-1',
        productId: 'prod-monaco-calfskin-sneaker',
        url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1200&q=80',
        altText: 'Monaco White Calfskin Sneaker side profile',
        order: 0,
      },
    ],
    variants: [
      {
        id: 'var-snk-wht-41',
        productId: 'prod-monaco-calfskin-sneaker',
        sku: 'MONACO-WHT-41',
        price: 165,
        compareAtPrice: 200,
        stock: 7,
        image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Color: 'Optic White', Size: 'EU 41' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'var-snk-wht-42',
        productId: 'prod-monaco-calfskin-sneaker',
        sku: 'MONACO-WHT-42',
        price: 165,
        compareAtPrice: 200,
        stock: 12,
        image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Color: 'Optic White', Size: 'EU 42' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },

  // ==================== WOMEN'S CLOTHES ====================
  {
    id: 'prod-atelier-silk-slip-dress',
    tenantId: 'tenant-milan',
    categoryId: 'cat-women-clothes',
    title: 'Atelier Mulberry Silk Crepe Slip Dress',
    slug: 'atelier-mulberry-silk-crepe-slip-dress',
    description: 'Tailored in Milan from 19-momme pure mulberry silk crepe-de-chine. Bias-cut to drape fluidly around the body with delicate French seams and adjustable silk spaghetti straps.',
    basePrice: 210,
    compareAtPrice: 265,
    isFeatured: true,
    status: 'ACTIVE',
    seoScore: 97.0,
    seoTitle: 'Atelier Mulberry Silk Crepe Slip Dress — Milan Haute Craft | Volvelo',
    seoDescription: '100% 19-momme Italian mulberry silk bias-cut slip dress. Elegant evening drape with French seams.',
    tags: ['women', 'clothes', 'dresses', 'silk', 'milan', 'luxury'],
    viewsCount: 3800,
    cartAddCount: 520,
    ordersCount: 198,
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2025-01-05'),
    images: [
      {
        id: 'img-silk-1',
        productId: 'prod-atelier-silk-slip-dress',
        url: 'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=1200&q=80',
        altText: 'Atelier Silk Slip Dress in Champagne Gold',
        order: 0,
      },
    ],
    variants: [
      {
        id: 'var-silk-gold-s',
        productId: 'prod-atelier-silk-slip-dress',
        sku: 'SILK-GLD-S',
        price: 210,
        compareAtPrice: 265,
        stock: 5,
        image: 'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Color: 'Champagne Gold', Size: 'S' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'var-silk-gold-m',
        productId: 'prod-atelier-silk-slip-dress',
        sku: 'SILK-GLD-M',
        price: 210,
        compareAtPrice: 265,
        stock: 8,
        image: 'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Color: 'Champagne Gold', Size: 'M' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'var-silk-blk-s',
        productId: 'prod-atelier-silk-slip-dress',
        sku: 'SILK-BLK-S',
        price: 210,
        compareAtPrice: 265,
        stock: 6,
        image: 'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Color: 'Noir Black', Size: 'S' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 'prod-cashmere-knit-sweater',
    tenantId: 'tenant-milan',
    categoryId: 'cat-women-clothes',
    title: 'Pure Cashmere Ribbed Mockneck Sweater',
    slug: 'pure-cashmere-ribbed-mockneck-sweater',
    description: 'Spun from Grade-A Cariaggi Italian cashmere. Incredibly soft, featherlight warmth with a refined ribbed mockneck and raglan shoulders.',
    basePrice: 185,
    compareAtPrice: 230,
    isFeatured: true,
    status: 'ACTIVE',
    seoScore: 94.0,
    seoTitle: 'Pure Cashmere Ribbed Mockneck Sweater | Volvelo',
    seoDescription: '100% Cariaggi Italian cashmere knitwear. Ultra-soft mockneck sweater tailored in Milan.',
    tags: ['women', 'clothes', 'knitwear', 'cashmere', 'sweater'],
    viewsCount: 2100,
    cartAddCount: 290,
    ordersCount: 95,
    createdAt: new Date('2025-01-12'),
    updatedAt: new Date('2025-01-12'),
    images: [
      {
        id: 'img-csh-1',
        productId: 'prod-cashmere-knit-sweater',
        url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=1200&q=80',
        altText: 'Cashmere Knit Sweater in Oatmeal Beige',
        order: 0,
      },
    ],
    variants: [
      {
        id: 'var-csh-oat-s',
        productId: 'prod-cashmere-knit-sweater',
        sku: 'CSH-OAT-S',
        price: 185,
        compareAtPrice: 230,
        stock: 7,
        image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Color: 'Oatmeal Beige', Size: 'S' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'var-csh-oat-m',
        productId: 'prod-cashmere-knit-sweater',
        sku: 'CSH-OAT-M',
        price: 185,
        compareAtPrice: 230,
        stock: 9,
        image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Color: 'Oatmeal Beige', Size: 'M' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 'prod-wool-atelier-overcoat',
    tenantId: 'tenant-milan',
    categoryId: 'cat-women-clothes',
    title: 'Double-Breasted Double-Faced Wool Coat',
    slug: 'double-breasted-double-faced-wool-coat',
    description: 'Constructed from heavy 650 GSM virgin double-faced wool. Hand-stitched edges, horn buttons, and relaxed structural drape.',
    basePrice: 360,
    compareAtPrice: 440,
    isFeatured: false,
    status: 'ACTIVE',
    seoScore: 92.5,
    seoTitle: 'Double-Faced Wool Atelier Coat | Volvelo',
    seoDescription: 'Hand-stitched Italian double-faced wool overcoat with horn buttons and tailored lapel.',
    tags: ['women', 'clothes', 'outerwear', 'wool-coat', 'luxury'],
    viewsCount: 1540,
    cartAddCount: 180,
    ordersCount: 52,
    createdAt: new Date('2025-01-22'),
    updatedAt: new Date('2025-01-22'),
    images: [
      {
        id: 'img-coat-1',
        productId: 'prod-wool-atelier-overcoat',
        url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=1200&q=80',
        altText: 'Double-Faced Wool Coat in Camel',
        order: 0,
      },
    ],
    variants: [
      {
        id: 'var-coat-cml-s',
        productId: 'prod-wool-atelier-overcoat',
        sku: 'COAT-CML-S',
        price: 360,
        compareAtPrice: 440,
        stock: 3,
        image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Color: 'Camel Tan', Size: 'S' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 'prod-tailored-high-rise-trousers',
    tenantId: 'tenant-volvelo',
    categoryId: 'cat-women-clothes',
    title: 'Tailored High-Rise Pleated Wool Trousers',
    slug: 'tailored-high-rise-pleated-wool-trousers',
    description: 'Cut with a flattering high-waist and deep front pleats that create an elongated silhouette. Woven with Italian fresco wool for breathable all-year structure.',
    basePrice: 145,
    compareAtPrice: 180,
    isFeatured: false,
    status: 'ACTIVE',
    seoScore: 90.0,
    seoTitle: 'Tailored High-Rise Pleated Wool Trousers | Volvelo',
    seoDescription: 'High-waisted Italian fresco wool trousers with crisp center press pleats.',
    tags: ['women', 'clothes', 'trousers', 'tailored', 'wool'],
    viewsCount: 1750,
    cartAddCount: 210,
    ordersCount: 68,
    createdAt: new Date('2025-01-25'),
    updatedAt: new Date('2025-01-25'),
    images: [
      {
        id: 'img-trs-1',
        productId: 'prod-tailored-high-rise-trousers',
        url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=80',
        altText: 'Tailored Pleated Trousers in Charcoal',
        order: 0,
      },
    ],
    variants: [
      {
        id: 'var-trs-blk-s',
        productId: 'prod-tailored-high-rise-trousers',
        sku: 'TRS-BLK-S',
        price: 145,
        compareAtPrice: 180,
        stock: 6,
        image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Color: 'Charcoal Noir', Size: 'S' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },

  // ==================== WOMEN'S WATCHES ====================
  {
    id: 'prod-milanese-rosegold-watch',
    tenantId: 'tenant-geneva',
    categoryId: 'cat-women-watches',
    title: 'Milanese Rose Gold Petite Dial Watch 30mm',
    slug: 'milanese-rose-gold-petite-dial-watch',
    description: 'Gleaming in 18k rose gold plating with a woven Milanese magnetic mesh band and mother-of-pearl dial. Assembled with Swiss quartz accuracy.',
    basePrice: 260,
    compareAtPrice: 320,
    isFeatured: true,
    status: 'ACTIVE',
    seoScore: 96.0,
    seoTitle: 'Milanese Rose Gold Petite Dial Watch 30mm | Volvelo',
    seoDescription: 'Swiss-assembled 30mm rose gold watch featuring a mother-of-pearl dial and Milanese mesh bracelet.',
    tags: ['women', 'watches', 'rose-gold', 'milanese', 'swiss-made', 'petite'],
    viewsCount: 3400,
    cartAddCount: 460,
    ordersCount: 172,
    createdAt: new Date('2025-01-09'),
    updatedAt: new Date('2025-01-09'),
    images: [
      {
        id: 'img-w-watch-1',
        productId: 'prod-milanese-rosegold-watch',
        url: 'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&w=1200&q=80',
        altText: 'Milanese Rose Gold Watch in Mother of Pearl dial',
        order: 0,
      },
    ],
    variants: [
      {
        id: 'var-rg-mop',
        productId: 'prod-milanese-rosegold-watch',
        sku: 'WATCH-RG-MOP',
        price: 260,
        compareAtPrice: 320,
        stock: 8,
        image: 'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&w=1200&q=80',
        optionValues: { 'Dial Metal': '18K Rose Gold', 'Dial Face': 'Mother of Pearl' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'var-rg-slv',
        productId: 'prod-milanese-rosegold-watch',
        sku: 'WATCH-SLV-MOP',
        price: 245,
        compareAtPrice: 300,
        stock: 5,
        image: 'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&w=1200&q=80',
        optionValues: { 'Dial Metal': 'Sterling Silver', 'Dial Face': 'Silver Sunray' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 'prod-diamond-accent-leather-watch',
    tenantId: 'tenant-geneva',
    categoryId: 'cat-women-watches',
    title: 'Classic Diamond-Marker 28mm Leather Watch',
    slug: 'classic-diamond-marker-28mm-leather-watch',
    description: 'Understated luxury with genuine VS1 diamond hour markers and a hand-stitched French alligator-embossed leather band.',
    basePrice: 340,
    compareAtPrice: 410,
    isFeatured: false,
    status: 'ACTIVE',
    seoScore: 91.5,
    seoTitle: 'Classic Diamond-Marker 28mm Leather Watch | Volvelo',
    seoDescription: '28mm Swiss timepiece with certified diamond markers and sapphire glass.',
    tags: ['women', 'watches', 'diamond', 'leather', 'classic'],
    viewsCount: 1400,
    cartAddCount: 160,
    ordersCount: 45,
    createdAt: new Date('2025-01-21'),
    updatedAt: new Date('2025-01-21'),
    images: [
      {
        id: 'img-w-watch-2',
        productId: 'prod-diamond-accent-leather-watch',
        url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80',
        altText: 'Classic Diamond Dial Watch with black leather strap',
        order: 0,
      },
    ],
    variants: [
      {
        id: 'var-dia-blk-28',
        productId: 'prod-diamond-accent-leather-watch',
        sku: 'DIA-BLK-28',
        price: 340,
        compareAtPrice: 410,
        stock: 4,
        image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80',
        optionValues: { 'Dial Metal': 'Polished Steel', Strap: 'Noir Leather' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },

  // ==================== WOMEN'S SHOES ====================
  {
    id: 'prod-italian-stiletto-pumps',
    tenantId: 'tenant-firenze',
    categoryId: 'cat-women-shoes',
    title: 'Artisan Florence 85mm Leather Stiletto Pumps',
    slug: 'artisan-florence-85mm-leather-stiletto-pumps',
    description: 'Sculpted in Florence with a timeless pointed toe, arch-supporting memory leather insole, and flawless Italian kidskin leather upper. 85mm stiletto heel perfectly balanced for evening comfort.',
    basePrice: 225,
    compareAtPrice: 280,
    isFeatured: true,
    status: 'ACTIVE',
    seoScore: 95.5,
    seoTitle: 'Artisan Florence 85mm Leather Stiletto Pumps | Volvelo',
    seoDescription: 'Handcrafted Italian kidskin leather pumps with ergonomic insole and 85mm stiletto heel.',
    tags: ['women', 'shoes', 'heels', 'pumps', 'made-in-italy', 'florence'],
    viewsCount: 2900,
    cartAddCount: 380,
    ordersCount: 135,
    createdAt: new Date('2025-01-06'),
    updatedAt: new Date('2025-01-06'),
    images: [
      {
        id: 'img-pump-1',
        productId: 'prod-italian-stiletto-pumps',
        url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1200&q=80',
        altText: 'Florence 85mm Stiletto Pumps in Noir Nappa',
        order: 0,
      },
    ],
    variants: [
      {
        id: 'var-pump-blk-38',
        productId: 'prod-italian-stiletto-pumps',
        sku: 'PUMP-BLK-38',
        price: 225,
        compareAtPrice: 280,
        stock: 5,
        image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Color: 'Noir Nappa', Size: 'EU 38' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'var-pump-blk-39',
        productId: 'prod-italian-stiletto-pumps',
        sku: 'PUMP-BLK-39',
        price: 225,
        compareAtPrice: 280,
        stock: 7,
        image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Color: 'Noir Nappa', Size: 'EU 39' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 'prod-milan-pointed-leather-flats',
    tenantId: 'tenant-firenze',
    categoryId: 'cat-women-shoes',
    title: 'Milano Pointed-Toe Glove Leather Flats',
    slug: 'milano-pointed-toe-glove-leather-flats',
    description: 'Soft-as-a-glove lambskin pointed flats hand-stitched in Tuscany. Features an elongated vamp and zero-drop leather sole for all-day chic.',
    basePrice: 170,
    compareAtPrice: 210,
    isFeatured: false,
    status: 'ACTIVE',
    seoScore: 91.0,
    seoTitle: 'Milano Pointed-Toe Glove Leather Flats | Volvelo',
    seoDescription: 'Handmade Tuscan pointed flats crafted from buttery soft Italian lambskin.',
    tags: ['women', 'shoes', 'flats', 'loafers', 'leather'],
    viewsCount: 1600,
    cartAddCount: 190,
    ordersCount: 62,
    createdAt: new Date('2025-01-16'),
    updatedAt: new Date('2025-01-16'),
    images: [
      {
        id: 'img-flat-1',
        productId: 'prod-milan-pointed-leather-flats',
        url: 'https://images.unsplash.com/photo-1560343090-f0409e92791a?auto=format&fit=crop&w=1200&q=80',
        altText: 'Milano Pointed Flats in Olive Earth',
        order: 0,
      },
    ],
    variants: [
      {
        id: 'var-flat-blk-38',
        productId: 'prod-milan-pointed-leather-flats',
        sku: 'FLAT-BLK-38',
        price: 170,
        compareAtPrice: 210,
        stock: 6,
        image: 'https://images.unsplash.com/photo-1560343090-f0409e92791a?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Color: 'Onyx Black', Size: 'EU 38' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 'prod-chelsea-calfskin-ankle-boots',
    tenantId: 'tenant-firenze',
    categoryId: 'cat-women-shoes',
    title: 'Tuscan Calfskin Chelsea Ankle Boots',
    slug: 'tuscan-calfskin-chelsea-ankle-boots',
    description: 'Weather-sealed French calfskin with Italian stretch-gore panels and Vibram commando lightweight rubber outsoles.',
    basePrice: 275,
    compareAtPrice: 335,
    isFeatured: true,
    status: 'ACTIVE',
    seoScore: 93.0,
    seoTitle: 'Tuscan Calfskin Chelsea Ankle Boots | Volvelo',
    seoDescription: 'Handcrafted Chelsea boots with weather-sealed Italian leather and Vibram traction soles.',
    tags: ['women', 'shoes', 'boots', 'chelsea', 'leather'],
    viewsCount: 2200,
    cartAddCount: 280,
    ordersCount: 88,
    createdAt: new Date('2025-01-23'),
    updatedAt: new Date('2025-01-23'),
    images: [
      {
        id: 'img-boot-1',
        productId: 'prod-chelsea-calfskin-ankle-boots',
        url: 'https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?auto=format&fit=crop&w=1200&q=80',
        altText: 'Tuscan Chelsea Boots in Espresso Brown',
        order: 0,
      },
    ],
    variants: [
      {
        id: 'var-boot-brn-38',
        productId: 'prod-chelsea-calfskin-ankle-boots',
        sku: 'BOOT-BRN-38',
        price: 275,
        compareAtPrice: 335,
        stock: 4,
        image: 'https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Color: 'Espresso Brown', Size: 'EU 38' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },

  // ==================== WOMEN'S FINE JEWELLERY ====================
  {
    id: 'prod-gold-sculptural-drop-earrings',
    tenantId: 'tenant-paris',
    categoryId: 'cat-women-jewellery',
    title: '18K Solid Gold Sculptural Drop Earrings',
    slug: '18k-solid-gold-sculptural-drop-earrings',
    description: 'Forged in Paris by master goldsmiths using recycled 18k solid yellow gold. High-mirror polish with organic architectural curves that catch light effortlessly.',
    basePrice: 190,
    compareAtPrice: 240,
    isFeatured: true,
    status: 'ACTIVE',
    seoScore: 98.0,
    seoTitle: '18K Solid Gold Sculptural Drop Earrings — Paris Haute Craft | Volvelo',
    seoDescription: 'Handcrafted in Place Vendôme. 18k recycled solid gold drop earrings with mirror finish and secure butterfly clasp.',
    tags: ['women', 'jewellery', 'earrings', 'gold', '18k', 'paris', 'bestseller'],
    viewsCount: 4200,
    cartAddCount: 590,
    ordersCount: 235,
    createdAt: new Date('2025-01-04'),
    updatedAt: new Date('2025-01-04'),
    images: [
      {
        id: 'img-earring-1',
        productId: 'prod-gold-sculptural-drop-earrings',
        url: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1200&q=80',
        altText: '18K Solid Gold Drop Earrings front perspective',
        order: 0,
      },
      {
        id: 'img-earring-2',
        productId: 'prod-gold-sculptural-drop-earrings',
        url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=80',
        altText: 'Gold Earrings pair on minimalist stone podium',
        order: 1,
      },
    ],
    variants: [
      {
        id: 'var-ear-18k-gold',
        productId: 'prod-gold-sculptural-drop-earrings',
        sku: 'EAR-18K-YEL',
        price: 190,
        compareAtPrice: 240,
        stock: 12,
        image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Metal: '18K Yellow Gold', Finish: 'High Polish' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'var-ear-18k-rose',
        productId: 'prod-gold-sculptural-drop-earrings',
        sku: 'EAR-18K-ROS',
        price: 190,
        compareAtPrice: 240,
        stock: 7,
        image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Metal: '18K Rose Gold', Finish: 'High Polish' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'var-ear-925-slv',
        productId: 'prod-gold-sculptural-drop-earrings',
        sku: 'EAR-925-SLV',
        price: 135,
        compareAtPrice: 170,
        stock: 15,
        image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Metal: '925 Sterling Silver', Finish: 'Rhodium Plated' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 'prod-solitaire-diamond-necklace',
    tenantId: 'tenant-paris',
    categoryId: 'cat-women-jewellery',
    title: 'Solitaire Lab-Grown Diamond 18K Pendant Necklace',
    slug: 'solitaire-lab-grown-diamond-pendant-necklace',
    description: 'A 0.50 ct brilliant-cut ethical lab diamond (F color, VVS1 clarity) set in a 4-prong 18k solid gold basket on a delicate diamond-cut cable chain.',
    basePrice: 320,
    compareAtPrice: 395,
    isFeatured: true,
    status: 'ACTIVE',
    seoScore: 96.5,
    seoTitle: 'Solitaire Diamond 18K Pendant Necklace | Volvelo',
    seoDescription: '0.50ct F-VVS1 ethical diamond pendant in 18k solid gold with adjustable 16-18" chain.',
    tags: ['women', 'jewellery', 'necklace', 'diamond', '18k', 'pendant'],
    viewsCount: 3100,
    cartAddCount: 420,
    ordersCount: 158,
    createdAt: new Date('2025-01-07'),
    updatedAt: new Date('2025-01-07'),
    images: [
      {
        id: 'img-nck-1',
        productId: 'prod-solitaire-diamond-necklace',
        url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=80',
        altText: 'Solitaire Diamond Necklace on 18K Gold Chain',
        order: 0,
      },
    ],
    variants: [
      {
        id: 'var-nck-18k-gold',
        productId: 'prod-solitaire-diamond-necklace',
        sku: 'NCK-18K-GLD',
        price: 320,
        compareAtPrice: 395,
        stock: 6,
        image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Metal: '18K Yellow Gold', 'Chain Length': '16-18 Inch' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 'prod-emerald-pav-tennis-bracelet',
    tenantId: 'tenant-paris',
    categoryId: 'cat-women-jewellery',
    title: 'Micro-Pavé Lab Diamond Tennis Bracelet 18K',
    slug: 'micro-pave-lab-diamond-tennis-bracelet',
    description: 'Continuous river of brilliant-cut diamonds (2.00 tcw) handset in 4-prong low profile links with a concealed double safety clasp.',
    basePrice: 290,
    compareAtPrice: 360,
    isFeatured: true,
    status: 'ACTIVE',
    seoScore: 94.0,
    seoTitle: 'Micro-Pavé Diamond Tennis Bracelet 18K | Volvelo',
    seoDescription: '2.00 tcw conflict-free diamond tennis bracelet with concealed double safety clasp.',
    tags: ['women', 'jewellery', 'bracelet', 'diamond', 'tennis-bracelet'],
    viewsCount: 2400,
    cartAddCount: 310,
    ordersCount: 92,
    createdAt: new Date('2025-01-11'),
    updatedAt: new Date('2025-01-11'),
    images: [
      {
        id: 'img-brc-1',
        productId: 'prod-emerald-pav-tennis-bracelet',
        url: 'https://images.unsplash.com/photo-1611591475152-477d75be4f9d?auto=format&fit=crop&w=1200&q=80',
        altText: 'Diamond Tennis Bracelet in 18k White Gold',
        order: 0,
      },
    ],
    variants: [
      {
        id: 'var-brc-18k-wht-7',
        productId: 'prod-emerald-pav-tennis-bracelet',
        sku: 'BRC-18K-WHT-7',
        price: 290,
        compareAtPrice: 360,
        stock: 5,
        image: 'https://images.unsplash.com/photo-1611591475152-477d75be4f9d?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Metal: '18K White Gold', Length: '7.0 Inch' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 'prod-fluted-dome-gold-ring',
    tenantId: 'tenant-paris',
    categoryId: 'cat-women-jewellery',
    title: '18K Solid Gold Fluted Statement Dome Ring',
    slug: '18k-solid-gold-fluted-statement-dome-ring',
    description: 'Sculptural fluted croissant silhouette cast in recycled 18k solid gold with a comfortable hollowed comfort-fit interior.',
    basePrice: 160,
    compareAtPrice: 200,
    isFeatured: false,
    status: 'ACTIVE',
    seoScore: 92.0,
    seoTitle: '18K Solid Gold Fluted Statement Dome Ring | Volvelo',
    seoDescription: 'Hand-polished 18k solid gold fluted dome ring forged in Paris.',
    tags: ['women', 'jewellery', 'ring', 'gold', '18k', 'dome-ring'],
    viewsCount: 1900,
    cartAddCount: 260,
    ordersCount: 84,
    createdAt: new Date('2025-01-19'),
    updatedAt: new Date('2025-01-19'),
    images: [
      {
        id: 'img-ring-1',
        productId: 'prod-fluted-dome-gold-ring',
        url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=80',
        altText: '18K Gold Fluted Dome Ring on marble',
        order: 0,
      },
    ],
    variants: [
      {
        id: 'var-ring-6',
        productId: 'prod-fluted-dome-gold-ring',
        sku: 'RING-DOME-6',
        price: 160,
        compareAtPrice: 200,
        stock: 5,
        image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Metal: '18K Yellow Gold', 'Ring Size': 'US 6 / EU 52' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'var-ring-7',
        productId: 'prod-fluted-dome-gold-ring',
        sku: 'RING-DOME-7',
        price: 160,
        compareAtPrice: 200,
        stock: 8,
        image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=80',
        optionValues: { Metal: '18K Yellow Gold', 'Ring Size': 'US 7 / EU 54' },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
];

export const mockPromoCodes: PromoCode[] = [
  {
    id: 'promo-1',
    code: 'WELCOME20',
    description: '20% off entire luxury order for first-time shoppers',
    discountType: 'PERCENTAGE',
    discountValue: 20,
    minSpend: 100,
    isActive: true,
    expiresAt: '2026-12-31',
    maxUses: 500,
    usageCount: 142,
  },
  {
    id: 'promo-2',
    code: 'HAUTE10',
    description: '€10 flat discount on European artisan collections',
    discountType: 'FIXED',
    discountValue: 10,
    minSpend: 80,
    isActive: true,
    expiresAt: '2026-12-31',
    maxUses: 1000,
    usageCount: 388,
  },
  {
    id: 'promo-3',
    code: 'FREESHIP',
    description: 'Complimentary European Express Delivery',
    discountType: 'FREE_SHIPPING',
    discountValue: 4.9,
    minSpend: 0,
    isActive: true,
    expiresAt: '2026-12-31',
    maxUses: undefined,
    usageCount: 812,
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'VOL-88291',
    customerName: 'Sophie Van Der Bilt',
    customerEmail: 'sophie.vdb@amsterdam-lux.nl',
    customerPhone: '+31 6 5543 9021',
    shippingAddress: {
      fullName: 'Sophie Van Der Bilt',
      email: 'sophie.vdb@amsterdam-lux.nl',
      phone: '+31 6 5543 9021',
      addressLine1: 'Keizersgracht 421',
      addressLine2: 'Apt 3B',
      city: 'Amsterdam',
      state: 'North Holland',
      postalCode: '1016 EK',
      country: 'NL',
    },
    subtotal: 420,
    shippingFee: 0,
    discountAmount: 0,
    totalAmount: 420,
    status: 'PROCESSING',
    items: [
      {
        id: 'oi-1',
        orderId: 'ord-1001',
        productId: 'prod-geneva-chronograph',
        variantId: 'var-chrono-blk-leather',
        tenantId: 'tenant-geneva',
        title: 'Geneva Grand Automatic Chronograph 41mm',
        variantTitle: 'Onyx Black / Italian Calf Leather',
        sku: 'CHRONO-GEN-BLK-LTH',
        price: 420,
        quantity: 1,
        imageUrl: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=400&q=80',
        fulfillmentStatus: 'PENDING',
      },
    ],
    createdAt: new Date('2025-03-12T10:30:00Z'),
    updatedAt: new Date('2025-03-12T10:30:00Z'),
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: 'post-1',
    title: 'The Art of Swiss Horology: Inside the Geneva Watchmaking Workshop',
    slug: 'art-of-swiss-horology-geneva',
    excerpt: 'Step inside the historic Swiss atelier where master watchmakers hand-tune mechanical chronographs with micrometer precision.',
    content: '<p>In the quiet valleys of Geneva, master watchmakers dedicate hundreds of hours to assembling movements containing over 200 minuscule components...</p>',
    coverImage: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80',
    author: 'Marc Dufour',
    isPublished: true,
    publishedAt: new Date('2025-02-15'),
    tags: ['Horology', 'Swiss Made', 'Craftsmanship'],
    embeddedProductIds: ['prod-geneva-chronograph'],
    createdAt: new Date('2025-02-15'),
    updatedAt: new Date('2025-02-15'),
  },
  {
    id: 'post-2',
    title: 'Tuscan Cordwainers: Why Blake-Stitched Shoes Last a Lifetime',
    slug: 'tuscan-cordwainers-blake-stitch',
    excerpt: 'Why Florence remains the world capital of luxury leather craftsmanship and the timeless science behind Blake stitching.',
    content: '<p>Tuscany has been home to master cobblers since the Renaissance. Here is why full-grain box calf leather and Blake welt construction create unrivaled flexibility...</p>',
    coverImage: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=1200&q=80',
    author: 'Matteo Rossi',
    isPublished: true,
    publishedAt: new Date('2025-02-28'),
    tags: ['Footwear', 'Made In Italy', 'Heritage'],
    embeddedProductIds: ['prod-florence-oxford-shoe'],
    createdAt: new Date('2025-02-28'),
    updatedAt: new Date('2025-02-28'),
  },
];

export const mockReviews: ProductReview[] = [
  {
    id: 'rev-1',
    productId: 'prod-gold-sculptural-drop-earrings',
    authorName: 'Camille Dubois',
    authorLocation: 'Paris, France',
    rating: 5,
    title: 'Breathtaking 18k gold craftsmanship',
    comment: 'The weight and sculptural light reflection on these earrings are magnificent. True Paris high jewellery quality.',
    isVerifiedBuyer: true,
    helpfulCount: 24,
    createdAt: '2025-02-20',
  },
  {
    id: 'rev-2',
    productId: 'prod-geneva-chronograph',
    authorName: 'Frederik Lindqvist',
    authorLocation: 'Stockholm, Sweden',
    rating: 5,
    title: 'Exquisite automatic movement',
    comment: 'The 48-hour power reserve and scratch-resistant sapphire crystal make this my daily luxury watch. Arrived in 2 days from Switzerland.',
    isVerifiedBuyer: true,
    helpfulCount: 19,
    createdAt: '2025-02-22',
  },
];

export const mockAbandonedCarts: AbandonedCart[] = [];

export const mockUsers: UserAccount[] = [
  {
    id: 'user-primary-superadmin',
    clerkId: 'user_superadmin_primary',
    email: 'talha.shaikh.dev1@gmail.com',
    name: 'Talha Shaikh (Super Admin)',
    role: 'SUPER_ADMIN',
    tenantId: null,
    createdAt: new Date('2025-01-01'),
  },
  {
    id: 'user-merchant-geneva',
    clerkId: 'user_geneva_123',
    email: 'contact@horloger-geneve.ch',
    name: 'Marc Dufour (L Atelier Horloger)',
    role: 'MERCHANT',
    tenantId: 'tenant-geneva',
    createdAt: new Date('2025-01-05'),
  },
  {
    id: 'user-merchant-firenze',
    clerkId: 'user_firenze_456',
    email: 'info@calzaturefirenze.it',
    name: 'Matteo Rossi (Bottega Firenze)',
    role: 'MERCHANT',
    tenantId: 'tenant-firenze',
    createdAt: new Date('2025-01-10'),
  },
  {
    id: 'user-merchant-paris',
    clerkId: 'user_paris_789',
    email: 'joaillerie@hauteparure.fr',
    name: 'Claire Chevalier (Maison Haute Parure)',
    role: 'MERCHANT',
    tenantId: 'tenant-paris',
    createdAt: new Date('2025-01-12'),
  },
];

export const mockCategoryRequests: CategoryRequest[] = [];
